// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTRi3Qnhy0mWPl4I6isF7l_ajcLkkbcp0',
    appId: '1:307118808259:web:0209cce45469ab49149676',
    messagingSenderId: '307118808259',
    projectId: 'chatroom-cec10',
    authDomain: 'chatroom-cec10.firebaseapp.com',
    storageBucket: 'chatroom-cec10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT40jdcRiX4XsQydLPl24zPe1m-vBhgWQ',
    appId: '1:307118808259:android:2c1bad886b325df4149676',
    messagingSenderId: '307118808259',
    projectId: 'chatroom-cec10',
    storageBucket: 'chatroom-cec10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ2g1npqgP0Oyhf8bTSKSs0tftkUviK9A',
    appId: '1:307118808259:ios:0cc27660cd21384e149676',
    messagingSenderId: '307118808259',
    projectId: 'chatroom-cec10',
    storageBucket: 'chatroom-cec10.appspot.com',
    iosClientId: '307118808259-nsdikajdoarem2kgk910n10gerkqve3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatroom',
  );
}
